### ISSUE TITLE
MODZ

### ISSUE THREAD

**Issue by RealLifeWorks** [firelightning13/DDLC-MCRevengeMod#14]
cant u plssssssssssssssssssssssssssssss update it when u have a chance plsssss

**Comment by RealLifeWorks** [comment]
:(

**Comment by firelightning13** [comment]
Pretty sure I already mention that I discontinued this mod months ago.

**Comment by firelightning13** [comment]
Unless someone is taking over this mod, which no one does, yet...

**Comment by RealLifeWorks** [comment]
awwwww darn
